# Site wide configuration


# Site settings
title: Neurorepository for the UIC Department of Neurology
email: ckoch5@uic.edu
description: > # The UIC Neurology Neurorepository is a resource for interested neurologists and pyhsicians. This site aims to be both informational and technical in nature and will contain research materials as well as departmental updates.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://localhost:4000
#url: "http://neurorepository.uic.edu" # the base hostname & protocol for your site
timezone: 'America/Chicago'


locale: en_US
logo: site-logo.png
search: true

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: UIC Department of Neurology-- NeuroRepository
  email: ckoch5@uic.edu
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
